<a href="https://colab.research.google.com/github/hasanulazad-cloud/Mathematical-Statistical-Analysis-for-Data-Science/blob/main/Mathematical_%26_Statistical_Analysis_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mathematical & Statistical Analysis for Data Science

In [1]:
#Task 1 – Linear Algebra Implementation

#Dataset:

#Linear Algebra Dataset:
import numpy as np
vector_a = np.array([2, 4, 6])
vector_b = np.array([1, 3, 5])
matrix_a = np.array([
[2, 1, 3],
[1, 0, 2],
[4, 1, 1]
])
matrix_b = np.array([
[1, 2, 0],
[3, 1, 4],
[2, 5, 1]
])

#Activity:
# Using NumPy:
# Perform vector addition, subtraction, and dot product using vector_a and vector_b
# Perform matrix addition and matrix multiplication using matrix_a and matrix_b
# Calculate determinant of matrix_a
# If determinant of matrix_a is not equal to zero, then find inverse of matrix_a
# Compute eigenvalues and eigenvectors of matrix_a

def vector_operations(vector_a,vector_b):
    added_vectors = vector_a.__add__(vector_b)
    subtracted_vectors = vector_a.__sub__(vector_b)
    dot_product = np.dot(vector_a,vector_b)
    print(f"Vector Addition: {added_vectors}")
    print(f"Vector Subtraction: {subtracted_vectors}")
    print(f"Dot Product: {dot_product}")

def matrix_operations(matrix_a,matrix_b):
    matrix_addition = matrix_a + matrix_b
    matrix_multiplication = np.matmul(matrix_a , matrix_b)
    print(f"Matrix Addition = {matrix_addition}")
    print(f"Matrix Multiplicaion = {matrix_multiplication}")
    matrix_det = np.linalg.det(matrix_a)
    if matrix_det != 0:
        inverse = np.linalg.inv(matrix_a)
        print("\nInverse of matrix_a:")
        print(inverse)
    else:
        print("\nmatrix_a is singular. Inverse does not exist.")


eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

vector_operations(vector_a=vector_a,vector_b=vector_b)
matrix_operations(matrix_a=matrix_a, matrix_b=matrix_b)
print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)





Vector Addition: [ 3  7 11]
Vector Subtraction: [1 1 1]
Dot Product: 44
Matrix Addition = [[3 3 3]
 [4 1 6]
 [6 6 2]]
Matrix Multiplicaion = [[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]

Inverse of matrix_a:
[[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]

Eigenvalues:
[ 5.54138127 -2.         -0.54138127]

Eigenvectors:
[[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]


In [2]:
#Task 2 – Probability Concepts
# Activity:
# Using Python / NumPy / SciPy:
# Calculate probability of successful sales
# Demonstrate conditional probability using customer segments

# Dataset for above activity:

import numpy as np
from scipy.stats import bernoulli

sales_success = [0.65, 0.35]
customer_segments = ["Premium", "Regular"]
segment_purchase_probability = {
"Premium": 0.80,
"Regular": 0.50
}

# Probability of successful sale
prob_success = sales_success[0]

print("Probability of Successful Sale:")
print(prob_success)

# Simulate a sale using Bernoulli distribution
sale = bernoulli.rvs(prob_success)

print("\nSample Sale Outcome:")
print("Success" if sale == 1 else "Failure")

# Conditional Probability by Customer Segment
print("\nConditional Probabilities:")

for segment in customer_segments:
    conditional_prob = segment_purchase_probability[segment]
    print(f"P(Purchase | {segment}) = {conditional_prob}")

Probability of Successful Sale:
0.65

Sample Sale Outcome:
Success

Conditional Probabilities:
P(Purchase | Premium) = 0.8
P(Purchase | Regular) = 0.5


In [3]:
# Bayes Theorem

#data
# Probability Dataset for Customer Purchase Analysis
# P(A): Probability that a customer is Premium
P_A = 0.40
# P(B): Probability that a customer makes a purchase
P_B = 0.62
# P(B|A): Probability that a Premium customer makes a purchase
P_B_given_A = 0.80

#Bayes Theorem formula
P_A_given_B = (P_B_given_A * P_A) / P_B
print("P(Premium | Purchase) =", round(P_A_given_B, 4))
print("Percentage =", round(P_A_given_B * 100, 2), "%")

P(Premium | Purchase) = 0.5161
Percentage = 51.61 %


In [4]:
import numpy as np
from scipy.stats import binom

#Binomial

# Binomial Distribution Parameters - n = number of trials, p = probability of success
n_trials = 20
success_prob = 0.65

binomial_samples = np.random.binomial(
    n=n_trials,
    p=success_prob,
    size=1000
)

print("First 10 Binomial Samples:")
print(binomial_samples[:10])


mean, var = binom.stats(n_trials, success_prob, moments='mv')

print("\nBinomial Mean:", mean)
print("Binomial Variance:", var)

First 10 Binomial Samples:
[17 12 12  8 14 13 14 11 15  9]

Binomial Mean: 13.0
Binomial Variance: 4.549999999999999


In [5]:
import numpy as np

# Normal Distribution Parameters
normal_mean = 50
normal_std = 10

# Generate 1000 samples
normal_samples = np.random.normal(
    loc=normal_mean,
    scale=normal_std,
    size=1000
)

print("First 10 Normal Samples:")
print(normal_samples[:10])

print("\nSample Mean:", np.mean(normal_samples))
print("Sample Standard Deviation:", np.std(normal_samples))

First 10 Normal Samples:
[55.41641575 45.90700846 48.68375699 52.36372945 48.70651786 45.21815539
 45.11028242 43.65881533 38.51690952 45.10416013]

Sample Mean: 50.29898490297399
Sample Standard Deviation: 9.90842880451024


In [6]:
import numpy as np

# Uniform Distribution Parameters
uniform_low = 0
uniform_high = 1

# Generate 1000 samples
uniform_samples = np.random.uniform(
    low=uniform_low,
    high=uniform_high,
    size=1000
)

print("First 10 Uniform Samples:")
print(uniform_samples[:10])

print("\nSample Mean:", np.mean(uniform_samples))
print("Minimum Value:", np.min(uniform_samples))
print("Maximum Value:", np.max(uniform_samples))

First 10 Uniform Samples:
[0.91864743 0.37622266 0.51463337 0.45766986 0.30469911 0.57383487
 0.2078473  0.23158744 0.0931602  0.81814256]

Sample Mean: 0.5032980244635645
Minimum Value: 0.0004530310512909086
Maximum Value: 0.997360801062281


In [7]:
import numpy as np
import pandas as pd
from statistics import mean, median, multimode
from scipy.stats import skew, kurtosis

# Dataset
sales_data = [120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
              190, 200, 210, 195, 185, 175, 165, 155, 145, 135]

# Convert to NumPy array
sales = np.array(sales_data)

# Central Tendency
mean_value = np.mean(sales)
median_value = np.median(sales)
mode_value = multimode(sales_data)

# Dispersion
range_value = np.max(sales) - np.min(sales)
variance_value = np.var(sales)
std_dev = np.std(sales)

# Shape of Distribution
skewness_value = skew(sales)
kurtosis_value = kurtosis(sales)

# Print Results
print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)

print("\nRange:", range_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_dev)

print("\nSkewness:", skewness_value)
print("Kurtosis:", kurtosis_value)

# Interpretation
if skewness_value > 0:
    print("\nDataset is Positively Skewed.")
elif skewness_value < 0:
    print("\nDataset is Negatively Skewed.")
else:
    print("\nDataset is Symmetric.")

Mean: 165.5
Median: 165.0
Mode: [135, 145, 155, 165, 175]

Range: 90
Variance: 534.75
Standard Deviation: 23.124662159694356

Skewness: 0.030143346252736614
Kurtosis: -0.7069943289224954

Dataset is Positively Skewed.
